name: First Cron Job
on:
  # Triggers the workflow every 10 minutes
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  cron:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyspark==3.3.1 spark-nlp==5.1.0 numpy
    - name: Test the latest Spark NLP on latest PySpark
      run: |
        cd test
        python -m pytest -v -m fast *.py
