# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        pyspark_version: [ 3.0.*, 3.1.*, 3.2.*, 3.3.*, 3.4.* ]
        sparknlp_version: [ 3.4.4, 4.0.2, 4.1.0, 4.4.4, 5.0.2, 5.1.0 ]
        exclude:
          - pyspark_version: 3.3.*
            sparknlp_version: 3.4.3
          - pyspark_version: 3.3.*
            sparknlp_version: 3.4.4
      fail-fast: false

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyspark==${{ matrix.pyspark_version }} spark-nlp==${{ matrix.sparknlp_version }} numpy
    - name: Test Spark NLP ${{ matrix.sparknlp_version }} on PySpark ${{ matrix.pyspark_version }}
      run: |
        cd test
        python -m pytest -v -m fast *.py

