# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        version: [ 3.0.*, 3.1.*, 3.2.* , 3.3.* ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyspark==${{ matrix.version }} spark-nlp numpy
    - name: Test Spark NLP on PySpark ${{ matrix.version }}
      run: |
        cd test
        python -m pytest -v -m fast *.py

